add report

diff --git a/.github/workflows/e2eTests.yml b/.github/workflows/e2eTests.yml
--- a/.github/workflows/e2eTests.yml
+++ b/.github/workflows/e2eTests.yml
@@ -74,8 +74,20 @@ jobs:
         run: |
           docker cp 'com.monefy.app.lite_1.18.0-2208_minAPI21(nodpi)_apkmirror.com.apk' appium-container:/home/androidusr/monefy.apk
 
-      - name: Run Tests in a Docker Container
+      - name: Set Test Info in Appium Reporter Plugin (Initial)
         run: |
+          curl -X POST "http://127.0.0.1:4723/setTestInfo" \
+          -H "Content-Type: application/json" \
+          -d '{
+                "testName": "Android E2E Tests",
+                "testStatus": "running",
+                "error": ""
+              }' || echo "Failed to set test info"
+
+      - name: Run Tests in a Docker Container
+        id: run-tests
+        run: |
+          # Run tests
           docker run --rm \
             --network host \
             -v ${{ github.workspace }}:/workspace \
@@ -87,17 +99,25 @@ jobs:
             -e DEVICE_NAME="Samsung Galaxy S10" \
             -e UDID="${EMULATOR_ID}" \
             -e APP_PATH="/home/androidusr/monefy.apk" \
-            maven:3.9.6-eclipse-temurin-17 mvn clean test
+            maven:3.9.6-eclipse-temurin-17 mvn clean test || echo "TEST_FAILED=true" >> $GITHUB_ENV
 
-      - name: Set Test Info in Appium Reporter Plugin
+      - name: Set Final Test Info in Appium Reporter Plugin
         run: |
+          TEST_STATUS="PASSED"
+          ERROR_MSG=""
+          if [ "$TEST_FAILED" == "true" ]; then
+            TEST_STATUS="FAILED"
+            ERROR_MSG="Tests failed. Check logs for details."
+          fi
+
+          # Update test info with final status and any error messages
           curl -X POST "http://127.0.0.1:4723/setTestInfo" \
           -H "Content-Type: application/json" \
           -d '{
                 "testName": "Android E2E Tests",
-                "testStatus": "running",
-                "error": ""
-              }' || echo "Failed to set test info"
+                "testStatus": "'"${TEST_STATUS}"'",
+                "error": "'"${ERROR_MSG}"'"
+              }' || echo "Failed to update test info"
 
       - name: Download Test Report from Appium Server
         run: |
@@ -109,16 +129,9 @@ jobs:
             echo "Report downloaded successfully"
           else
             echo "Report not found!" && exit 1
-          fi
 
       - name: Upload Test Report
         uses: actions/upload-artifact@v4
         with:
           name: test-report
           path: report.html
-
-
-
-
-
-
