add report

diff --git a/.github/workflows/e2eTests.yml b/.github/workflows/e2eTests.yml
--- a/.github/workflows/e2eTests.yml
+++ b/.github/workflows/e2eTests.yml
@@ -89,20 +89,39 @@ jobs:
             -e APP_PATH="/home/androidusr/monefy.apk" \
             maven:3.9.6-eclipse-temurin-17 mvn clean test
 
+      - name: Set Execution Time
+        run: echo "EXEC_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
+
+      - name: Set Test Info in Appium Reporter Plugin
+        run: |
+          curl -X POST "http://127.0.0.1:4723/setTestInfo" \
+          -H "Content-Type: application/json" \
+          -d '{
+                "testName": "Android E2E Tests",
+                "executionTime": "'"${EXEC_TIME}"'",
+                "status": "running"
+              }' || echo "Failed to set test info"
+
       - name: Download Test Report from Appium Server
         run: |
-            curl -o report.html http://127.0.0.1:4723/getReport || echo "Failed to download report"
+          curl -o report.html http://127.0.0.1:4723/getReport || echo "Failed to download report"
 
       - name: Verify Report Exists
         run: |
-            if [ -f "report.html" ]; then
-               echo "Report downloaded successfully"
-            else
-               echo "Report not found!" && exit 1
-            fi
+          if [ -f "report.html" ]; then
+            echo "Report downloaded successfully"
+          else
+            echo "Report not found!" && exit 1
+          fi
 
       - name: Upload Test Report
         uses: actions/upload-artifact@v4
         with:
           name: test-report
           path: report.html
+
+
+
+
+
+
